name: CTest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up CMake build
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests with CTest
        run: ctest --test-dir build --output-on-failure
